Migrate Old (UserProfile.name_en) into (UserProfile.meta)
Edraak/edraak-platform pull request #154
Opened 2020-03-03 12:53 UTC by shadinaif

This is to copy database old data of **UserProfile.name_en** into **UserProfile.meta**, and then drop the old column (**name_en**)

If the column doesn't not exist (in devstack or in already-fixed data); this migration will be skipped

2020-03-03 14:44 UTC, ghost requested changes
Thanks @shadinaif! Please convert to a [Django management command](https://docs.djangoproject.com/en/3.0/howto/custom-management-commands/) instead. Here's why:

 - Add migrations on apps that we don't own (i.e. edX Apps like `students`) would mean that every time upstream makes a new migration we need to [create yet another "merge" migration](https://riptutorial.com/django/example/23659/solving-migration-conflicts). Merge migrations are very painful to deal with and I recommend avoiding them unless absolutely necessary.

 - The reason why we chose to override `meta` is to avoid having a new migration like what this PR is introducing.
 - Unlike migrations, Django commands do no run automatically, which is an acceptable compromise in my opinion.

Please let me know if you have any questions.

2020-03-03 15:27 UTC, shadinaif commented
All done @OmarEdraak . Please review again

2020-03-04 07:55 UTC, ghost approved these changes
`name_en` conflicts with the existing `@property def name_en`, so I used SQL aliases to solve the issue.

This saves us the effort to manually working with meta and use the `@name_en.setter` property instead.

See:

https://github.com/Edraak/edraak-platform/blob/db4d256e29bb204defff301d8ca394a8e62c5fc6/common/djangoapps/student/models.py#L465-L485

2020-03-04 07:55 UTC, OmarEdraak commented on common/djangoapps/student/management/commands/edraak_migrate_userprofile_name_en.py
> +                user_profile.save()
```suggestion
            for user_profile in old_data:
                user_profile.name_en = user_profile.DB_name_en
                user_profile.save()
```

2020-03-04 07:55 UTC, OmarEdraak commented on common/djangoapps/student/management/commands/edraak_migrate_userprofile_name_en.py
> +                "SELECT id, meta, name_en FROM auth_userprofile WHERE (name_en IS NOT NULL) AND (name_en != '');"
```suggestion
                "SELECT id, meta, name_en as DB_name_en FROM auth_userprofile WHERE (name_en IS NOT NULL) AND (name_en != '');"
```

2020-03-04 17:10 UTC, shadinaif commented on common/djangoapps/student/management/commands/edraak_migrate_userprofile_name_en.py
> +                user_profile.save()
Done

2020-03-04 17:10 UTC, shadinaif commented on common/djangoapps/student/management/commands/edraak_migrate_userprofile_name_en.py
> +                "SELECT id, meta, name_en FROM auth_userprofile WHERE (name_en IS NOT NULL) AND (name_en != '');"
Done

2020-03-05 07:29 UTC, ghost approved these changes

2020-03-05 08:31 UTC, merged