Change form strings
Edraak/edraak-platform pull request #212
Opened 2020-05-14 07:49 UTC by Salomari1987

2020-05-14 12:58 UTC, OmarEdraak commented
Thanks @Salomari1987. There's a couple of failed tests related to the change:

![image](https://user-images.githubusercontent.com/47500477/81936776-61e5c700-95fb-11ea-8730-63fa359e2e2e.png)

Could you please update the related tests to have just `Username`:

https://github.com/Edraak/edraak-platform/blob/efd4e68cc02928b10cf478d564b95d646141f4b4/openedx/core/djangoapps/user_api/tests/test_views.py#L1137

and 

https://github.com/Edraak/edraak-platform/blob/efd4e68cc02928b10cf478d564b95d646141f4b4/openedx/core/djangoapps/user_api/tests/test_views.py#L1340

2020-05-17 10:06 UTC, Fahminajjar requested changes

2020-05-17 10:06 UTC, Fahminajjar commented on conf/locale/en/LC_MESSAGES/djangojs.po
> +"cannot be undone. EdX will not be able to recover your account or the data "
Why EdX instead of Edraak?

2020-05-17 10:06 UTC, Fahminajjar commented on conf/locale/en/LC_MESSAGES/djangojs.po
> +"Once your account is deleted, you cannot use it to take courses on the edX "
Same here.

2020-05-17 10:06 UTC, Fahminajjar commented on conf/locale/en/LC_MESSAGES/djangojs.po
> +" data is permanent and cannot be undone. EdX will not be able to recover "
Same here.

2020-05-17 10:06 UTC, Fahminajjar commented on conf/locale/en/LC_MESSAGES/djangojs.po
> +"the edX app, edx.org, or any other site hosted by edX. This includes access "
Same here.

2020-05-17 10:09 UTC, Salomari1987 commented on conf/locale/en/LC_MESSAGES/djangojs.po
> +msgstr ""
Check these, I think these should be fine

2020-05-17 10:12 UTC, Fahminajjar approved these changes

2020-05-17 10:12 UTC, Fahminajjar commented on conf/locale/eo/LC_MESSAGES/djangojs.po
> +"cannot be undone. EdX will not be able to recover your account or the data "
Same here.

2020-05-17 10:12 UTC, merged