Add name_en field to account setting page
Edraak/edraak-platform pull request #241
Opened 2020-10-21 18:03 UTC by ahmadabuwardeh

### Description
The user should be able to add an Arabic and English full name from the "Account Settings"

## JIRA tickets
https://edraak.atlassian.net/browse/EC2020-655
https://edraak.atlassian.net/browse/EC2020-656

2020-10-22 12:04 UTC, Fahminajjar requested changes

2020-10-22 12:04 UTC, Fahminajjar commented on lms/envs/common.py
>  ENTERPRISE_READONLY_ACCOUNT_FIELDS = [
Is this for the user? I think it's something for enterprises right?

2020-10-22 12:04 UTC, Fahminajjar commented on openedx/core/djangoapps/api_admin/migrations/0008_auto_20201022_1449.py
> +class Migration(migrations.Migration):
What is this migration? I think it's not related to what you are doing right?

2020-10-22 12:04 UTC, Fahminajjar commented on openedx/core/djangoapps/credit/migrations/0005_auto_20201022_1449.py
> +class Migration(migrations.Migration):
Same with this migration.

2020-10-22 14:37 UTC, Fahminajjar commented
You just have to fix tests and make migrations for the new `name_en` field.

2020-10-27 09:15 UTC, Fahminajjar approved these changes

2020-10-27 09:22 UTC, Fahminajjar commented
LGTM, we'll merge it when we merge [this PR](https://github.com/Edraak/edraak-programs/pull/1537).

2020-11-04 07:08 UTC, Fahminajjar requested changes

2020-11-04 07:08 UTC, Fahminajjar commented on common/djangoapps/student/admin.py
> +    form = NameEnForm
This form is for the whole UserProfile no only for `name_en` field so it's better to call it `UserProfileWithNameEnForm` or something like that. What do you think?

2020-11-04 07:08 UTC, Fahminajjar commented on common/djangoapps/student/admin.py
> +    def save(self, commit=True):
Just add the model in the class Meta:
```python
class NameEnForm(forms.ModelForm):
    name_en = forms.CharField(required=False, widget=widgets.TextInput)

    class Meta:
        model = UserProfile

     ....
     def save(self, commit=True):
     ....
```

2020-11-04 07:08 UTC, Fahminajjar commented on common/djangoapps/student/admin.py
> +        super(NameEnForm, self).save()
You are not passing `save` method args and kwargs to the super `save`. I would recommend:
```python
def save(self, *args, **kwargs):
    ...
    super(NameEnForm, self).save(*args, **kwargs)
```

2020-11-04 07:42 UTC, Fahminajjar approved these changes

2020-11-04 09:04 UTC, Salomari1987 approved these changes

2020-11-04 09:10 UTC, Fahminajjar approved these changes

2020-11-04 09:10 UTC, merged