(WIP) Migrate Edraak certificates
Edraak/edraak-platform pull request #54
Opened 2017-07-31 07:30 UTC by OmarIthawi

### Description

TASK: [Migrate Edraak's PDF certificate with tests](https://app.asana.com/0/256944342521670/395647354508655)

### Testing

### Related PRs
- Example: [Configuration Pull #XX](github.com/edraak/configuration/pull/XX)

2017-08-08 13:16 UTC, OmarIthawi commented
@Salomari1987 Could you please take a look?

2017-08-10 11:28 UTC, OmarIthawi commented
Last ping @ahmedaljazzar and @Salomari1987. I'll merge by the end of day, if no one steps in.

2017-08-10 15:38 UTC, ahmedaljazzar commented on lms/djangoapps/edraak_certificates/generator.py
> +def generate_certificate(request, course):
Do you think it's a good idea to send a request object to a non-view function?

2017-08-13 08:27 UTC, OmarIthawi commented on lms/djangoapps/edraak_certificates/generator.py
> +def generate_certificate(request, course):
I hate to do this, but when an edX function requires it, I have no other solution.

2017-08-16 09:02 UTC, OmarIthawi commented
@ahmedaljazzar any other comments?

2017-08-16 10:54 UTC, iamjazzar requested changes

2017-08-16 10:54 UTC, ahmedaljazzar commented on lms/djangoapps/edraak_certificates/views.py
> +def view(request, course_id):
Rename it please to something else.

2017-08-16 10:54 UTC, ahmedaljazzar commented on lms/djangoapps/edraak_certificates/utils.py
> +        raise Exception('Please enable the organization app (`ORGANIZATIONS_APP`) in '
Can we change the exception message here to a more descriptive one like you enabled X without enabling Y.

2017-08-16 10:54 UTC, ahmedaljazzar commented on requirements/edx/base.txt
> +python-bidi==0.3.4
You can use my [python-arabic-reshaper](https://github.com/ahmedaljazzar/python-arabic-reshaper) if you want.

2017-08-16 11:43 UTC, OmarIthawi commented on lms/djangoapps/edraak_certificates/views.py
> +def view(request, course_id):
It's now `preview`.

2017-08-16 12:52 UTC, OmarIthawi commented on requirements/edx/base.txt
> +python-bidi==0.3.4
As much as I liked to use it, It has a bug:
```ValueError: Invalid configuration: A section with the name ArabicReshaper was not found```

I'm skipping this one.

2017-08-16 12:52 UTC, OmarIthawi commented on lms/djangoapps/edraak_certificates/utils.py
> +        raise Exception('Please enable the organization app (`ORGANIZATIONS_APP`) in '
Done

2017-08-16 12:52 UTC, OmarIthawi commented on lms/djangoapps/edraak_certificates/views.py
> +def view(request, course_id):
Done

2017-08-16 13:13 UTC, OmarIthawi commented
@ahmedaljazzar I've resolved your comments. Please add your checkmark here, or `dismiss` your review.

2017-08-16 13:19 UTC, iamjazzar approved these changes

2017-08-20 10:01 UTC, merged