API retrieve data from marketing (with tests and a feature flag)
Edraak/edraak-platform pull request #59
Opened 2017-08-29 11:57 UTC by OmarIthawi

### Description

TASK: [Migrate Ahmed's (API retrieve course data from marketing)](https://app.asana.com/0/256944342521670/379587353715604)

### TODO
- [x] Refactored with tests and a feature flag
- [ ] Manually tested

### Related PRs
- Migrates: https://github.com/Edraak/edx-platform/pull/258/commits/530e05ed9feffecd723bd45595ab48a4f0f8429e

2017-08-29 19:53 UTC, iamjazzar requested changes
Please check the tests as well.

2017-08-29 19:53 UTC, iamjazzar commented on lms/djangoapps/course_api/helpers.py
> +    marketing_api = 'api/marketing/courses/{}'.format(course_key)
Why don't we add the marketing APIs in the settings' json just like [marketing URLs](https://github.com/Edraak/edraak-platform/blob/master/lms/envs/aws.py#L300)?

2017-08-29 19:53 UTC, iamjazzar commented on lms/djangoapps/course_api/helpers.py
> +    marketing_api = 'api/marketing/courses/{}'.format(course_key)
Shouldn't the course key be `unicode`d before formatting?

2017-08-29 19:53 UTC, iamjazzar commented on lms/djangoapps/course_api/helpers.py
> +        return {}
It would be awesome if we logged why this failed here, it won't leave us guessing.

2017-08-29 19:53 UTC, iamjazzar commented on lms/djangoapps/course_api/views.py
> +    def get_serializer_class(self):
Shouldn't we mark this as an Edraak change?

2017-08-29 19:53 UTC, iamjazzar commented on lms/djangoapps/course_api/serializers.py
> +        overridden['effort'] = marketing_data['effort']
These are going to cost us a 500 error in case we decided to rename the field in the api, right?

2017-08-29 19:53 UTC, ahmedaljazzar commented on lms/djangoapps/course_api/tests/test_edraak_customizations.py
> +        self.assertFalse(helpers.is_marketing_api_enabled(), 'Should be enabled by default')
`Should be enabled by default`?

2017-08-30 09:01 UTC, OmarIthawi commented on lms/djangoapps/course_api/helpers.py
> +    marketing_api = 'api/marketing/courses/{}'.format(course_key)
> Shouldn't the course key be unicoded before formatting?
Not really. It's coerced.

2017-08-30 10:30 UTC, OmarIthawi commented on lms/djangoapps/course_api/views.py
> +    def get_serializer_class(self):
In very rare cases we do, normally when tests cannot be done. In this case there's a whole test file suite to ensure that, so no need.

2017-08-30 10:31 UTC, OmarIthawi commented on lms/djangoapps/course_api/serializers.py
> +        overridden['effort'] = marketing_data['effort']
Yes, and that's OK. It's better to fail explicitly rather than returning `None` suddenly!

2017-09-07 08:12 UTC, OmarIthawi commented
@ahmedaljazzar would you mind take another look here? It would also be great if we can test it to see how it works on mobile!

2017-09-07 08:15 UTC, OmarIthawi commented
@ahmedaljazzar if that's not possible today, then please quickly check my changes and approve when applicable.

2017-09-07 09:04 UTC, OmarIthawi commented
I'll merge now. I'm trying to wrap things up to prepare for QA, which should reveal issues in this code.

2017-09-07 09:05 UTC, merged